In [99]:
import os
import matplotlib.pyplot as plt
#To work with data frames
import pandas as pd

#To perform numerical operations
import numpy as np

#To visualize data
import seaborn as sns

#Importing library for logictic regression
from sklearn.linear_model import LogisticRegression
#to use train_test_split function
from sklearn.model_selection import train_test_split
#Importing performance metrics - accuracy score and confusion
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

os.chdir("D:\\program\\PYTHON\\CSV")
incomedata=pd.read_csv("income.csv")
data=incomedata.copy()
data2=data.dropna(axis=0)

In [19]:
## LOGISTIC REGRESSION
# mapping <=50,000 to 0 and >50,000 to 1 
data2["SalStat"]=data2["SalStat"].map({" less than or equal to 50,000":0," greater than 50,000":1})
print(data2)

       age       JobType         EdType        maritalstatus  \
0       45       Private        HS-grad             Divorced   
1       24   Federal-gov        HS-grad        Never-married   
2       44       Private   Some-college   Married-civ-spouse   
3       27       Private            9th        Never-married   
4       20       Private   Some-college        Never-married   
...    ...           ...            ...                  ...   
31973   34     Local-gov        HS-grad        Never-married   
31974   34     Local-gov   Some-college        Never-married   
31975   23       Private   Some-college   Married-civ-spouse   
31976   42     Local-gov   Some-college   Married-civ-spouse   
31977   29       Private      Bachelors        Never-married   

             occupation     relationship    race   gender  capitalgain  \
0          Adm-clerical    Not-in-family   White   Female            0   
1          Armed-Forces        Own-child   White     Male            0   
2        

In [20]:
print(data2["SalStat"].unique())

[0 1]


In [21]:
new_data=pd.get_dummies(data2,drop_first=True)
print(new_data)

       age  capitalgain  capitalloss  hoursperweek  SalStat  \
0       45            0            0            28        0   
1       24            0            0            40        0   
2       44            0            0            40        1   
3       27            0            0            40        0   
4       20            0            0            35        0   
...    ...          ...          ...           ...      ...   
31973   34          594            0            60        0   
31974   34            0            0            40        0   
31975   23            0            0            40        0   
31976   42            0            0            40        0   
31977   29            0            0            40        0   

       JobType_ Federal-gov  JobType_ Local-gov  JobType_ Never-worked  \
0                     False               False                  False   
1                      True               False                  False   
2                    

In [28]:
#storing the column names
columns_list=list(new_data.columns)
print(column_list)

['age', 'capitalgain', 'capitalloss', 'hoursperweek', 'SalStat', 'JobType_ Federal-gov', 'JobType_ Local-gov', 'JobType_ Never-worked', 'JobType_ Private', 'JobType_ Self-emp-inc', 'JobType_ Self-emp-not-inc', 'JobType_ State-gov', 'JobType_ Without-pay', 'EdType_ 11th', 'EdType_ 12th', 'EdType_ 1st-4th', 'EdType_ 5th-6th', 'EdType_ 7th-8th', 'EdType_ 9th', 'EdType_ Assoc-acdm', 'EdType_ Assoc-voc', 'EdType_ Bachelors', 'EdType_ Doctorate', 'EdType_ HS-grad', 'EdType_ Masters', 'EdType_ Preschool', 'EdType_ Prof-school', 'EdType_ Some-college', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-civ-spouse', 'maritalstatus_ Married-spouse-absent', 'maritalstatus_ Never-married', 'maritalstatus_ Separated', 'maritalstatus_ Widowed', 'occupation_ Adm-clerical', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupati

In [34]:
#separating the input names from data
features=list(set(columns_list)-set(["SalStat"]))
print(features)
print(len(features))

['nativecountry_ Dominican-Republic', 'relationship_ Other-relative', 'gender_ Male', 'race_ White', 'nativecountry_ France', 'nativecountry_ Hungary', 'JobType_ Self-emp-inc', 'nativecountry_ Taiwan', 'nativecountry_ Portugal', 'EdType_ 7th-8th', 'age', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'nativecountry_ China', 'nativecountry_ Scotland', 'occupation_ Prof-specialty', 'capitalloss', 'maritalstatus_ Married-AF-spouse', 'EdType_ Assoc-acdm', 'nativecountry_ Haiti', 'capitalgain', 'occupation_ Machine-op-inspct', 'nativecountry_ South', 'EdType_ Some-college', 'nativecountry_ England', 'occupation_ Protective-serv', 'nativecountry_ Germany', 'maritalstatus_ Separated', 'EdType_ Masters', 'EdType_ HS-grad', 'nativecountry_ Peru', 'nativecountry_ Ecuador', 'race_ Other', 'nativecountry_ Laos', 'occupation_ Sales', 'occupation_ Other-service', 'JobType_ Federal-gov', 'nativecountry_ Iran', 'EdType_ 1st-4th', 'occupation_ Armed-Forces', 'relationship_ Own-child', 

In [35]:
#Storing the output values in y
y=new_data["SalStat"].values
print(y)

[0 0 1 ... 0 0 0]


In [36]:
#Storing the values from input features
x=new_data[features].values
print(x)

[[False False False ... False False False]
 [False False True ... False False False]
 [False False True ... False False False]
 ...
 [False False True ... False False False]
 [False False False ... False False False]
 [False False True ... False False False]]


In [41]:
#Splitting the data into train and test
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.3,random_state=0)
print(train_x,"\n\n",test_x,"\n\n",train_y,"\n\n",test_y)

[[False True False ... False False False]
 [False False False ... False False False]
 [False False True ... False False False]
 ...
 [False False True ... False False False]
 [False False True ... False False False]
 [False False True ... False False False]] 

 [[False False True ... False False False]
 [False True True ... False False False]
 [False False True ... False False False]
 ...
 [False False True ... False False False]
 [False False False ... False False False]
 [False False False ... False False True]] 

 [0 0 0 ... 0 1 0] 

 [0 0 1 ... 0 0 0]


In [42]:
#make an instance of the model
logistic=LogisticRegression()
print(logistic)

LogisticRegression()


In [51]:
#fitting the values for x and y
logistic.fit(train_x,train_y)


C:\Users\raamp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [52]:
logistic.coef_

array([[-3.50212950e-02, -3.18147053e-01,  7.21107385e-02,
        -3.59408014e-01,  1.33295607e-02, -1.16391668e-04,
         2.00720820e-01, -8.01034468e-03, -2.73364265e-02,
        -4.01101470e-01,  5.05217555e-04, -4.38323341e-01,
        -3.88212589e-01, -3.53549502e-02, -4.07801893e-03,
         8.35506024e-01,  5.29325559e-04,  2.13569620e-02,
        -3.27612506e-05, -2.01852940e-02,  3.31469630e-04,
        -4.12236285e-01, -4.82644607e-02, -3.08766902e-01,
         1.23215281e-03,  6.84767132e-03,  1.11944448e-02,
        -2.04899536e-01,  6.68032061e-01, -1.00479446e+00,
        -1.35547224e-02, -8.81166007e-03, -1.21232422e-01,
        -1.16794616e-02,  2.53415514e-01, -7.98727900e-01,
         1.68809396e-01, -4.00854263e-03, -1.00734211e-01,
        -4.61916023e-03, -1.12178313e+00, -4.89476066e-02,
        -1.07074169e-03, -4.84949172e-01, -5.53076313e-02,
        -7.51301382e-03, -6.83367698e-01, -2.16737880e-01,
         1.02723726e+00, -9.37861759e-02,  1.06882865e+0

In [53]:
logistic.intercept_

array([-1.30355674])

In [59]:
#prediction from test data
prediction=logistic.predict(test_x)
print(prediction)

[0 0 0 ... 0 0 0]


In [63]:
#confusion matric- It gives you the both no.of correct and incorrect predictions
confusion_matrix=confusion_matrix(test_y,prediction)
print(confusion_matrix)

[[6828  508]
 [ 932 1326]]


In [66]:
#calculating the accuracy
score=accuracy_score(test_y,prediction)
print(score)

0.849906191369606


In [68]:
# printing the misclassified values from prediction

print("Misclassified samples: %d" %(test_y != prediction).sum())

Misclassified samples: 1440


In [69]:
##LOGISTIC REGRESSION - REMOVING INSIGNIFICANT VARIABLES

In [71]:
#reindexing the salary status names to 0,1
data2["SalStat"]=data2["SalStat"].map({" less than or equal to 50,000":0," greater than 50,000":1})
print(data2["SalStat"])

0        0
1        0
2        1
3        0
4        0
        ..
31973    0
31974    0
31975    0
31976    0
31977    0
Name: SalStat, Length: 31978, dtype: int64


In [74]:
cols=["gender","nativecountry","race","JobType"]
new_data=data2.drop(cols,axis=1)
print(new_data)

       age         EdType        maritalstatus        occupation  \
0       45        HS-grad             Divorced      Adm-clerical   
1       24        HS-grad        Never-married      Armed-Forces   
2       44   Some-college   Married-civ-spouse    Prof-specialty   
3       27            9th        Never-married      Craft-repair   
4       20   Some-college        Never-married             Sales   
...    ...            ...                  ...               ...   
31973   34        HS-grad        Never-married   Farming-fishing   
31974   34   Some-college        Never-married   Protective-serv   
31975   23   Some-college   Married-civ-spouse      Adm-clerical   
31976   42   Some-college   Married-civ-spouse      Adm-clerical   
31977   29      Bachelors        Never-married    Prof-specialty   

          relationship  capitalgain  capitalloss  hoursperweek  SalStat  
0        Not-in-family            0            0            28        0  
1            Own-child            0

In [75]:
new_data=pd.get_dummies(new_data,drop_first=True)
print(new_data)

       age  capitalgain  capitalloss  hoursperweek  SalStat  EdType_ 11th  \
0       45            0            0            28        0         False   
1       24            0            0            40        0         False   
2       44            0            0            40        1         False   
3       27            0            0            40        0         False   
4       20            0            0            35        0         False   
...    ...          ...          ...           ...      ...           ...   
31973   34          594            0            60        0         False   
31974   34            0            0            40        0         False   
31975   23            0            0            40        0         False   
31976   42            0            0            40        0         False   
31977   29            0            0            40        0         False   

       EdType_ 12th  EdType_ 1st-4th  EdType_ 5th-6th  EdType_ 7th-8th  ...

In [76]:
#storing the column names
columns_list=list(new_data.columns)
print(columns_list)

['age', 'capitalgain', 'capitalloss', 'hoursperweek', 'SalStat', 'EdType_ 11th', 'EdType_ 12th', 'EdType_ 1st-4th', 'EdType_ 5th-6th', 'EdType_ 7th-8th', 'EdType_ 9th', 'EdType_ Assoc-acdm', 'EdType_ Assoc-voc', 'EdType_ Bachelors', 'EdType_ Doctorate', 'EdType_ HS-grad', 'EdType_ Masters', 'EdType_ Preschool', 'EdType_ Prof-school', 'EdType_ Some-college', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-civ-spouse', 'maritalstatus_ Married-spouse-absent', 'maritalstatus_ Never-married', 'maritalstatus_ Separated', 'maritalstatus_ Widowed', 'occupation_ Adm-clerical', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv', 'occupation_ Prof-specialty', 'occupation_ Protective-serv', 'occupation_ Sales', 'occupation_ Tech-support', 'occupation_ Transport-moving', 'relationship_ Not-in-famil

In [77]:
#Separating the input names from data
features=list(set(columns_list)-set(["SalStat"]))
print(features)

['maritalstatus_ Married-spouse-absent', 'relationship_ Other-relative', 'maritalstatus_ Married-civ-spouse', 'hoursperweek', 'relationship_ Not-in-family', 'EdType_ 7th-8th', 'EdType_ 12th', 'age', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Prof-specialty', 'relationship_ Wife', 'capitalloss', 'maritalstatus_ Married-AF-spouse', 'occupation_ Adm-clerical', 'EdType_ Assoc-acdm', 'relationship_ Unmarried', 'capitalgain', 'occupation_ Priv-house-serv', 'occupation_ Machine-op-inspct', 'EdType_ Some-college', 'maritalstatus_ Never-married', 'occupation_ Protective-serv', 'maritalstatus_ Separated', 'occupation_ Craft-repair', 'EdType_ 9th', 'EdType_ Masters', 'EdType_ 5th-6th', 'EdType_ Assoc-voc', 'EdType_ HS-grad', 'occupation_ Sales', 'occupation_ Other-service', 'EdType_ Doctorate', 'EdType_ Bachelors', 'EdType_ Preschool', 'EdType_ Prof-school', 'EdType_ 1st-4th', 'occupation_ Armed-Forces', 'maritalstatus_ Widowed', 'relationship_ Own-child', 'EdTyp

In [78]:
#Storing the output valus to y
y=new_data["SalStat"].values
print(y)

[0 0 1 ... 0 0 0]


In [79]:
#Storing the values from the input features
x=new_data[features].values
print(x)

[[False False False ... False False False]
 [False False False ... False False False]
 [False False True ... False False False]
 ...
 [False False True ... False False False]
 [False False True ... False False False]
 [False False False ... False False False]]


In [81]:
#Splitting the data into train and test
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.3,random_state=False)

print(train_x,"\n\n",test_x,"\n\n",train_y,"\n\n",test_y)

[[False True False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False True ... False False False]
 [False False False ... False False False]] 

 [[False False False ... True False False]
 [True True False ... False False False]
 [False False True ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False True]] 

 [0 0 0 ... 0 1 0] 

 [0 0 1 ... 0 0 0]


In [85]:
#Make an instance of the model
logistic=LogisticRegression()
#Fitting the values for x and y
logistic.fit(train_x,train_y)

C:\Users\raamp\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [90]:
#prediction from test data
prediction=logistic.predict(test_x)
print(prediction)

[0 0 0 ... 0 0 0]


In [91]:
#Calculating the accuracy
accuracy_score=accuracy_score(test_y,prediction)
print(accuracy_score)

0.847196164269335


In [93]:
#Printing the misclassified values from prediction
print("Misclassified samples: %d" %(test_y!=prediction).sum())

Misclassified samples: 1466


In [ ]:
#KNN

In [97]:
#importing the library of knn
from sklearn.neighbors import KNeighborsClassifier
#importing library for plotting
import matplotlib.pyplot as plt

#Storing the k nearest neighbors classifier
KNN_classifier=KNeighborsClassifier(n_neighbors=5)

#fitting the values for x and y
KNN_classifier.fit(train_x,train_y)

#predicting the test values with model
prediction=KNN_classifier.predict(test_x)
print(prediction)

[0 0 0 ... 0 0 0]


In [101]:
#performance metric check
confusion_matrix=confusion_matrix(test_y,prediction)
print("\tPredicted values")
print("Original values\n",confusion_matrix)

	Predicted values
Original values
 [[6702  634]
 [ 894 1364]]


In [102]:
#Calculating the accuracy 
accuracy_score=accuracy_score(test_y,prediction)
print(accuracy_score)

0.8407337919533041


In [103]:
# printing the misclassified values from prediction

print("Misclassified samples: %d" %(test_y != prediction).sum())

Misclassified samples: 1528


In [105]:
'''Effect of k value classifier'''
misclassifiedsample=[]
#calculating error for k values between 1 and 20
for i in range(1,20):
    knn=KNeighborsClassifier(n_neighbors=i)
    knn.fit(train_x,train_y)
    pred_i=knn.predict(test_x)
    misclassifiedsample.append((test_y!=pred_i).sum())
print(misclassifiedsample)

[1751, 1500, 1588, 1512, 1528, 1467, 1456, 1460, 1478, 1465, 1464, 1455, 1457, 1419, 1445, 1418, 1418, 1418, 1406]
