In [3]:
print("Hello World")

Hello World


In [1]:
print("hii")

hii


In [2]:
a=[1,2,3,4,5]
for i in a:
    print(i)

1
2
3
4
5


In [4]:
from array import *
arr=array('i',[1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


In [5]:
print(arr)

array('i', [1, 2, 3, 4, 5])


In [6]:
arr[5]=6
print(arr)

IndexError: array assignment index out of range

In [7]:
arr[4]=6
print(arr)

array('i', [1, 2, 3, 4, 6])


In [8]:
print(arr[:3])

array('i', [1, 2, 3])


In [9]:
print(arr[2:])

array('i', [3, 4, 6])


In [25]:
lis=[1,2,3,4,5]
print(lis)
lis.append(6)
print(lis)
lis+=[6,7]
print(lis)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 6, 7]


In [23]:
tup=1,2,3,4
tup+=5,6,7,8
print(tup)

(1, 2, 3, 4, 5, 6, 7, 8)


In [28]:
lis1=[1,2,3]
print("list1:",lis1*2)

list1: [1, 2, 3, 1, 2, 3]


In [17]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype=int,ndmin=1)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12],dtype=int,ndmin=1)
print(arr)
arr2=arr.reshape(3,4)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
print(arr2.shape)

(3, 4)


In [28]:
arr3=arr.reshape(6,-1)
print(arr3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [31]:
lis1=[1,2,3]
lis2=[4,5,6]
lis3=[7,8,9]
arr4=np.array([lis1,lis2,lis3])
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
arr5=np.arange(1,26,3)
print(arr5.reshape(3,-1))


[[ 1  4  7]
 [10 13 16]
 [19 22 25]]


In [50]:
lis1=[1,2,3]
lis2=[4,5,6]
lis3=[7,8,9]
arr4=np.array([lis1,lis2,lis3])
arr5=arr4
print(arr4,"\n")
print(arr5,"\n")
print(arr4+arr5)#print(np.add(arr4,arr5))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [46]:
print(arr4-arr5)#print(np.subtract(arr4,arr5))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [51]:
print(arr4*arr5)#print(np.multiply(arr4,arr5))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [49]:
print(np.dot(arr4,arr5))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [52]:
print(arr4/arr5)#print(np.divide(arr4,arr5))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [55]:
print(np.sum(arr4))

45


In [54]:
print(np.sum(arr4,axis=0))

[12 15 18]


In [56]:
print(np.sum(arr4,axis=1))

[ 6 15 24]
